SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_INS AS AI JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.DATETIME > AO.DATETIME
ORDER BY AI.DATETIME

/*
뭔가 기본키로 JOIN하는 게 맞는 것 같네요.
그리고 DATETIME은 크기 비교를 <, > = 로 할 수 있나봅니다.
*/
